#!/bin/sh
#
# A simple script to start dwm in a while-loop, allowing dwm 
# to be restarted on-the-fly without closing other X applications
#
# Usage:    killall dwm         # restart dwm on-the-fly
#           killall startdwm    # kill X session

dwm_dir=${HOME}/.dwm

conky -c ${dwm_dir}/conkyrc | while read line; do
    xsetroot -name "$line"; 
# log stderror to a file 
done | while true; do ${dwm_dir}/dwm 2> ${dwm_dir}/dwm.err; done;
# no error logging
#done | while true; do dwm > /dev/null; done;
